# Generated by Django 5.2.12 on 2026-04-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctor_phone_alter_doctor_specialization_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('pediatrican', 'Pediatrican'), ('orthopedist', 'Orthopedist')], max_length=30),
        ),
    ]
